function [CN_TOTAL, CD_TOTAL, COP_TOTAL] = CoeffCalculator(V,A)
% FROM BARROWMAN REPORT

% Dimensions of nose, body and fins (m)
LEN_NOSECONE = 150*10^-3;
ROOTCHORD_FIN = 85*10^-3;
TIPCHORD_FIN = 50*10^-3;
AVERAGECHORD_FIN = (ROOTCHORD_FIN + TIPCHORD_FIN)/2;
THICKNESS_FIN = 0.238*10^-3;
HEIGHT_FIN = 53*10^-3;
MIDCHORD_FIN = 53*10^-3;
SWEEPANGLE_FIN = 24*pi/180;
SWEEPLENGTH_FIN = 23.3*10^-3;
AREA_FIN = (ROOTCHORD_FIN + TIPCHORD_FIN)/2 * HEIGHT_FIN * 4;
DIAMETER_BODY = 60*10^-3;
LEN_ROCKET = 1140*10^-3;
KINEMATIC_VISC = 1.495*10^-5;
AREA_FRONTBODY = pi*DIAMETER_BODY^2/4;

% Normal force coeff for body, fins, nosecone (per radian)
CN_NOSE = 2;
CN_BODY = 0;
CN_FINS = 16*(HEIGHT_FIN/DIAMETER_BODY)^2 / (1 + sqrt(1 + (2*MIDCHORD_FIN / (ROOTCHORD_FIN + TIPCHORD_FIN))^2));
%correction 
K = 1  +TIPCHORD_FIN/(HEIGHT_FIN + TIPCHORD_FIN);
CN_INTERFERENCE = K*CN_FINS;
CN_TOTAL = CN_INTERFERENCE + CN_BODY + CN_NOSE + CN_FINS;



% COP calculation
COP_NOSE = 0.466.*[0, 0, LEN_NOSECONE]; %Vertical vec for now 
%relative to tip CHORD
COP_FINS_TIP = (SWEEPLENGTH_FIN/3) * ((ROOTCHORD_FIN + 2*TIPCHORD_FIN) / (ROOTCHORD_FIN + TIPCHORD_FIN)) + ...
                (1/6)*(ROOTCHORD_FIN + TIPCHORD_FIN - (ROOTCHORD_FIN*TIPCHORD_FIN)/(ROOTCHORD_FIN + TIPCHORD_FIN));

COP_FINS = [0,0,COP_FINS_TIP+(LEN_ROCKET-ROOTCHORD_FIN)]; %from nose cone
COP_INTERFERENCE = [0,0,LEN_ROCKET-ROOTCHORD_FIN]; %from nose cone

COP_TOTAL = (COP_INTERFERENCE.*CN_INTERFERENCE + COP_FINS.*CN_FINS + COP_NOSE.*CN_NOSE)/CN_TOTAL; %FROM NOSE TIP

% drag force coeff for body, fins, nosecone 
% FROM MANDEL'S TOPICS IN ADVANCED ROCKETRY (PG 447)
Re_B = V * LEN_ROCKET/KINEMATIC_VISC;
B = 5*10^5*(0.73/Re_B^(1/5) - 1.328/sqrt(Re_B));
SKINFRICTION_BODY = 0.73/Re_B^(1/5) - B/Re_B;
AREA_RATIO = 4*(LEN_ROCKET-LEN_NOSECONE)/DIAMETER_BODY + 2.7*LEN_NOSECONE/DIAMETER_BODY;
F = 1 + 60/(LEN_ROCKET/DIAMETER_BODY)^3 + 0.0025*LEN_ROCKET/DIAMETER_BODY;
CD_FB = SKINFRICTION_BODY*F*AREA_RATIO; %forbody body drag
CD_DB = 0.029*(1/1)^3/sqrt(CD_FB); %forbody base drag
Re_F = V * AVERAGECHORD_FIN / KINEMATIC_VISC;
SKINFRICTION_FIN = 1.328/sqrt(Re_F);
TC_RATIO = THICKNESS_FIN / AVERAGECHORD_FIN;
CD_F = 2*SKINFRICTION_FIN*(1+2*TC_RATIO)*AREA_FIN/AREA_FRONTBODY;
Ma = V/A;
if(Ma<1)
    CD_TOTAL = (CD_F + CD_DB + CD_FB)*(1/sqrt(1 - Ma^2));
else
    CD_TOTAL = (CD_F + CD_DB + CD_FB)*(1/sqrt(Ma^2 - 1));
end
end